### ISSUE TITLE
BUG: Games are not closed.

### ISSUE THREAD

**Issue by YannickBR** [Kraanter/PeopleParty#58]
**Describe the bug**
The games are not closed, so when a code is already open it goes into the game directly.

**To Reproduce**
1. Refresh until you join a game with a code open.

**Expected behavior**
A new game should always appear.

**Screenshots**

**Additional context**

**Comment by JCDriessen** [comment]
Bug is fixed on the branch /feature/better-minigame-loop. Will be implemented when this branch goes to staging/main in ~2 days.
